######################################################################
#
# File name : rgb2gray_tb.udo
# Created on: Thu Nov 12 20:01:27 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
