######################################################################
#
# File name : rgb2gray_tb_wave.do
# Created on: Thu Nov 12 20:25:08 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
