######################################################################
#
# File name : rgb2gray_tb_compile.do
# Created on: Thu Nov 12 20:25:04 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../rgb2gray.ip_user_files/ip/fifo_generator_1/fifo_generator_1_sim_netlist.v" \
"../../../rgb2gray.ip_user_files/ip/fifo_generator_0/fifo_generator_0_sim_netlist.v" \
"../../../src/RGB2YCbCr.v" \
"../../../src/video_cap.v" \
"../../../src/image_src.v" \
"../../../src/rgb2gray.v" \
"../../../src/rgb2gray_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

